Hotfix: 63 git hub templates
UAL-ODIS/ReQUIAM_csv pull request #69
Opened 2021-02-18 22:45 UTC by damian-romero

See #63

Add the latest version of PR and ISSUE templates from LD_Cool-P
Fix links to work with this repository

2021-02-19 18:28 UTC, astrochun requested changes
Changes look good but see one suggestion below.

2021-02-19 18:28 UTC, astrochun commented on .github/ISSUE_TEMPLATE/bug_report.md
> + - `numpy` version: [e.g., 1.19.5]
```suggestion
**Version information**
<!-- Update with tagged version or branch full name-->
[requirements](https://github.com/ualibraries/ReQUIAM_csv/blob/v<version>/requirements.txt)
[requirements](https://github.com/ualibraries/ReQUIAM_csv/blob/<branch>/requirements.txt)
```

2021-02-19 19:30 UTC, astrochun reviewed
Looks good, but here's the problem, the branch name is incorrect now that I look at it. It won't easily allow for versioning via `git-flow` so I have to fix that. Please be consistent with branch names within `git-flow`

2021-02-19 19:30 UTC, astrochun approved these changes

2021-02-23 16:31 UTC, damian-romero commented
Fixed in #70

2021-02-23 16:31 UTC, closed without merging